# Generated by Django 5.0.2 on 2024-02-19 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_course_creator_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='course', to='education.singlecontent'),
        ),
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_course', through='education.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
