# Generated by Django 5.0.2 on 2024-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
