# Generated by Django 5.0.2 on 2024-02-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_content_alter_course_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creator',
            new_name='user',
        ),
    ]
