# Generated by Django 5.0.2 on 2024-02-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_rename_creator_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='singlecontent',
            old_name='creator',
            new_name='user',
        ),
    ]
