# Generated by Django 5.0.2 on 2024-03-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
