# Generated by Django 5.0.2 on 2024-02-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_rename_user_course_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='user',
            new_name='participant',
        ),
    ]
