# Generated by Django 5.0.2 on 2024-02-20 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_rename_user_participation_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
