# Generated by Django 5.0.2 on 2024-03-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('russian', 'Russian'), ('mandarin', 'Mandarin'), ('turkish', 'Turkish')], default='english', max_length=50),
        ),
    ]
