# Generated by Django 5.0.2 on 2024-03-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='singlecontent',
            name='url_youtube',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
