# Generated by Django 5.0.2 on 2024-02-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_user_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
