# Generated by Django 5.0.2 on 2024-02-24 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_user_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('single_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='education.singlecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_left', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
